---
# main tasks file for win2019-base role

- name: Ensure firewall is enabled on all profiles
  community.windows.win_firewall:
    state: enabled
    profiles: "{{ win2019_base_firewall_profiles }}"

- name: Set timezone to GMT Standard Time
  community.windows.win_timezone:
    timezone: "{{ win2019_base_timezone }}"

- name: Set DNS lookup
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "{{ win2019_base_resolvers }}"
  when: win2019_base_update_resolvers

- name: Install packages
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ win2019_base_packages }}"
    state: present
